type User {
    id: ID!
    createdAt: String!
    updatedAt: String!

    email: String!
    username: String!
    password: String!
    firstname: String!
    lastname: String!
    posts: [Post!]!
}

type Query {
    users: [User!]!
}